esphome:
  name: test-comp
  build_path: /config/esphome/build/test-comp
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.6.0.zip
  includes:
    - test_comp.h
  
esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    version: 5.2.1
    #https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32s3/api-reference/kconfig.html#config-esp-console-uart
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ZB_ENABLED: y
      CONFIG_ZB_ZED: y
      CONFIG_ZB_RADIO_NATIVE: y
      ZB_ED_ROLE: y
  variant: esp32c6

external_components:
  - source: github://luar123/esphome@fix_logger
    components: [ logger ]

logger:
  level: INFO
  hardware_uart: UART0

custom_component:
- lambda: |-
    auto tc = new TestComponent();
    return {tc};
  components:
    - id: testcomp
